volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  open-webui:
  pgadmin_data:

networks:
  demo:
    driver: bridge
    internal: true # Make this network isolated
  external_net:
    driver: bridge
    internal: false # This network can access the internet

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks:
    - demo
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    - N8N_RUNNERS_ENABLED=true
  links:
    - postgres

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks:
    - demo
    - external_net
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    - ollama_storage:/root/.ollama
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:11434/"]
    interval: 10s
    timeout: 5s
    retries: 10
  #environment:
  # experimental features to decrease RAM usage:
  #- OLLAMA_FLASH_ATTENTION=true
  #- OLLAMA_KV_CACHE_TYPE=f16
  #- OLLAMA_MAX_LOADED_MODELS=1

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks:
    - demo
    - external_net
  container_name: ollama-pull-llama
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-c"
    # https://gist.github.com/ibnbd/5ec32ce14bde8484ca466b7d77e18764#best-practices
    - |
      # Wait for Ollama service to be ready
      sleep 3

      # Pull large language models
      #OLLAMA_HOST=ollama:11434 ollama pull mistral-small3.1:24b
      OLLAMA_HOST=ollama:11434 ollama pull qwen3:30b-a3b-q4_K_M
      OLLAMA_HOST=ollama:11434 ollama pull qwen3-vl:32b
      #OLLAMA_HOST=ollama:11434 ollama pull gemma3:27b-it-qat
      #OLLAMA_HOST=ollama:11434 ollama pull devstral:24b

      # Pull embedding model
      OLLAMA_HOST=ollama:11434 ollama pull bge-m3

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - demo
      - external_net
    restart: unless-stopped
    container_name: open-webui
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
      - ./open-webui-functions-for-import.json:/app/backend/functions-export.json:ro
      - ./scripts/open-webui-entrypoint.sh:/docker-entrypoint.sh:ro
    environment:
      - DEFAULT_LOCALE=en
      - WEBUI_ADMIN_EMAIL=${WEBUI_ADMIN_EMAIL}
      - WEBUI_ADMIN_USER=${WEBUI_ADMIN_USER}
      - WEBUI_ADMIN_PASS=${WEBUI_ADMIN_PASS}
    entrypoint: ["/bin/bash", "/docker-entrypoint.sh"]

  postgres:
    image: pgvector/pgvector:pg16
    networks:
      - demo
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:9.3.0
    container_name: pgadmin
    networks:
      - demo
      - external_net
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        n8n import:workflow --input=/backup/AI_Agent_With_Knowledge_Base_Main.json
        n8n import:workflow --input=/backup/AI_Agent_With_Knowledge_Base_Final.json
    volumes:
      - ./n8n/backup:/backup
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    container_name: n8n
    networks:
      - demo
      - external_net
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-pull-llama-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *init-ollama
    depends_on:
      - ollama-gpu

  docling:
    image: quay.io/docling-project/docling-serve
    container_name: docling-serve
    networks:
      - demo
      - external_net
    restart: unless-stopped
    ports:
      - 5001:5001
    environment:
      - DOCLING_SERVE_ENABLE_UI=true
      - DOCLING_SERVE_MAX_DOCUMENT_TIMEOUT=1800 # 30 minutes
      - DOCLING_SERVE_MAX_SYNC_WAIT=2100 # 35 minutes
      #- DOCLING_SERVE_MAX_NUM_PAGES=50
      #- DOCLING_SERVE_MAX_FILE_SIZE=15728640 # 15MB
    depends_on:
      - n8n
